### ISSUE TITLE
Dockerfile should be start from capital letter

### ISSUE THREAD

**Issue by tshimba** [kgb1001001/minecraft-project#2]
I got error when I type `sudo docker build -t="<directory>/minecraft188" .` on my Mac.

My environment
```
$ docker --version
Docker version 1.12.3, build 6b644ec
$ docker-compose --version
docker-compose version 1.8.1, build 878cff1
$ docker-machine --version
docker-machine version 0.8.2, build e18a919
```

macOS Sierra Version 10.12.1

**Comment by kgb1001001** [comment]
This has been fixed in the latest release.  Most Docker versions would be fine with either capitalized or not, but the mac version may have been uniquely sensitive.  You should be able to use the latest build which now uses capital letters to avoid this issue.
